"""empty message

Revision ID: 47e6b3a4504
Revises: None
Create Date: 2015-03-18 01:17:19.919376

"""

# revision identifiers, used by Alembic.
revision = '47e6b3a4504'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
